# Generated by Django 3.1 on 2024-08-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240728_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_date',
            new_name='created_date',
        ),
    ]
